### PR TITLE
iOS 13 support

### PR DESCRIPTION
**Pull request by KingPuffdaddi**
Added hooks needed for iOS 13
Updated implementation of CustomMenu to show on iOS 13

### CODE REVIEW

**Comment by trungking** [comment]
Thank you for updating to ios 13, I've been waiting too long 
I have tested it and it worked but in some site, it crash safari and after crashing, it stop wroking, need respring to work again
Crashlog here 
https://gist.github.com/trungking/3d84a78544e78c46a4723476013dcb54

And can you make an ignore button? Just ignore it, neither save to blacklist nor whitelist

**Comment by trungking** [comment]
The issue has been resolved.
I hope the maintainer is still here, merge this pr and update it to bigboss

**Comment by DroomOne** [comment]
I'm still here! I'll upload the new version to bigboss, thanks @KingPuffdaddi for updating the tweak to iOS 13!

**Comment by trungking** [comment]
thank you

**Pull request merged**
